/**
 * Created by Haoyu Guo on 2016/9/27.
 */
/**
 * Created by gmyth on 16/9/9.
 */
/*inpt data temporarily to check the functionality */
define(function(require, exports, module){
    exports.data = {
        Course:[
            {
                "_id": "57e54188304ddf23ffcdc6a9",
                "status": "Open",
                "Room": "Hoch 114",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "A",
                "instructors": "*  Hartloff, J L",
                "Days": "M W",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "4:00 PM  -  4:50 PM",
                "Type": "SEM",
                "Class": "<<<  >>>"
            },
            {
                "_id": "57e54188304ddf23ffcdc6aa",
                "status": "Closed",
                "Room": "Norton 214",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "A1",
                "instructors": "Staff",
                "Days": "T",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "9:00 AM  -  9:50 AM",
                "Type": "REC",
                "Class": "24441"
            },
            {
                "_id": "57e54188304ddf23ffcdc6ab",
                "status": "Closed",
                "Room": "Norton 214",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "A2",
                "instructors": "Staff",
                "Days": "T",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "10:00 AM  -  10:50 AM",
                "Type": "REC",
                "Class": "24442"
            },
            {
                "_id": "57e54188304ddf23ffcdc6ac",
                "status": "Closed",
                "Room": "Hoch 307",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "A3",
                "instructors": "Staff",
                "Days": "M",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "9:00 AM  -  9:50 AM",
                "Type": "REC",
                "Class": "24443"
            },
            {
                "_id": "57e54188304ddf23ffcdc6ae",
                "status": "Open",
                "Room": "Knox 110",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "B",
                "instructors": "*  Hertz, M",
                "Days": "M W",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "4:00 PM  -  4:50 PM",
                "Type": "SEM",
                "Class": "<<<  >>>"
            },
            {
                "_id": "57e54188304ddf23ffcdc6ad",
                "status": "Closed",
                "Room": "Cooke 248",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "A4",
                "instructors": "Staff",
                "Days": "M",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "8:00 AM  -  8:50 AM",
                "Type": "REC",
                "Class": "24444"
            },
            {
                "_id": "57e54188304ddf23ffcdc6af",
                "status": "Closed",
                "Room": "Norton 209",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "B1",
                "instructors": "Staff\n                                             * Hughes, A R",
                "Days": "R",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "9:00 AM  -  9:50 AM",
                "Type": "REC",
                "Class": "24440"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b0",
                "status": "Closed",
                "Room": "Norton 209",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "B2",
                "instructors": "Staff\n                                             * Hughes, A R",
                "Days": "R",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "10:00 AM  -  10:50 AM",
                "Type": "REC",
                "Class": "24445"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b1",
                "status": "Closed",
                "Room": "Alumni 88",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "B4",
                "instructors": "*  Winikus, J",
                "Days": "R",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "12:00 PM  -  12:50 PM",
                "Type": "REC",
                "Class": "24447"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b2",
                "status": "Open w/ Reserves",
                "Room": "Davis 338A",
                "Title": "Ub Seminar",
                "Section": "B5",
                "instructors": "Staff\n                                             * Qiao, C",
                "Days": "F",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "10:00 AM  -  10:50 AM",
                "Type": "REC",
                "Class": "25695"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b5",
                "status": "Closed",
                "Room": "Norton 209",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "C2",
                "instructors": "Staff\n                                             * Hughes, A R",
                "Days": "F",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "11:00 AM  -  11:50 AM",
                "Type": "REC",
                "Class": "24448"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b6",
                "status": "Closed",
                "Room": "Talbrt 111",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "C3",
                "instructors": "Staff\n                                             * Hughes, A R",
                "Days": "R",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "1:00 PM  -  1:50 PM",
                "Type": "REC",
                "Class": "24449"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b4",
                "status": "Closed",
                "Room": "Davis 113A",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "C1",
                "instructors": "Staff\n                                             * Hughes, A R",
                "Days": "F",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "12:00 PM  -  12:50 PM",
                "Type": "REC",
                "Class": "24439"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b7",
                "status": "Closed",
                "Room": "Baldy 109",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "C4",
                "instructors": "Staff\n                                             * Hughes, A R",
                "Days": "R",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "2:00 PM  -  2:50 PM",
                "Type": "REC",
                "Class": "24450"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b3",
                "status": "Closed",
                "Room": "Nsc 210",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "C",
                "instructors": "*  Winikus, J",
                "Days": "M W",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "4:00 PM  -  4:50 PM",
                "Type": "SEM",
                "Class": "<<<  >>>"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b8",
                "status": "Open",
                "Room": "Alumni 97",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "D",
                "instructors": "*  Hughes, A R",
                "Days": "M W",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "9:00 AM  -  9:50 AM",
                "Type": "SEM",
                "Class": "<<<  >>>"
            },
            {
                "_id": "57e54188304ddf23ffcdc6b9",
                "status": "Open",
                "Room": "Clemen 103",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "D1",
                "instructors": "Staff",
                "Days": "T",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "8:00 AM  -  8:50 AM",
                "Type": "REC",
                "Class": "25331"
            },
            {
                "_id": "57e54188304ddf23ffcdc6bb",
                "status": "Open w/ Reserves",
                "Room": "Clemen 103",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "D3",
                "instructors": "Staff",
                "Days": "T",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "3:00 PM  -  3:50 PM",
                "Type": "REC",
                "Class": "25333"
            },
            {
                "_id": "57e54188304ddf23ffcdc6ba",
                "status": "Open w/ Reserves",
                "Room": "Park 146",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "D2",
                "instructors": "Staff",
                "Days": "T",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "5:00 PM  -  5:50 PM",
                "Type": "REC",
                "Class": "25332"
            },
            {
                "_id": "57e54188304ddf23ffcdc6bc",
                "status": "Open w/ Reserves",
                "Room": "Alumni 88",
                "Title": "Ub Seminar-How The Internet Works",
                "Section": "D4",
                "instructors": "Staff",
                "Days": "T",
                "Course": "CSE 199SR",
                "Location": "North Campus",
                "Time": "4:00 PM  -  4:50 PM",
                "Type": "REC",
                "Class": "25334"
            }
        ]
    };
});